### ISSUE TITLE
[Feature Request] Add Emoji Methods

### ISSUE THREAD

**Issue by seailz** [discord-jv/discord.jv#19]
### General Troubleshooting

- [X] You've have checked for similar feature requests.
- [X] You've updated to the latest version of the API.
- [X] You've have checked the PR's for features relating to your suggestion.

### Feature Request Description

https://discord.com/developers/docs/resources/emoji#list-guild-emojis

**Comment by Blueysh** [comment]
Can this be closed or are you expecting to add more?
