### ISSUE TITLE
[Bug Report] command listener being run twice

### ISSUE THREAD

**Issue by seailz** [discord-jv/discord.jv#66]
### General Troubleshooting

- [X] You've have checked for similar issues.
- [X] You've updated to the latest version of the API
- [X] You've have checked the PR's for bug fixes relating to your issue.

### Part of library impacted

Commands

### Bug Report Description

Command listeners are being run twice

### Steps to reproduce

N/A

**Comment by seailz** [comment]
Line 80 in command dispatcher

**Comment by Blueysh** [comment]
i'm skimming very quickly, but it looks like the same code is run in both line 80 & 82

**Comment by seailz** [comment]
> i'm skimming very quickly, but it looks like the same code is run in both line 80 & 82

exactly
